#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: package OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      url:
        description: 'OpenWrt Repository URL'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      branch:
        description: 'OpenWrt Repository Branch'
        required: true
        default: 'master'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: ${{github.event.inputs.url}}
  REPO_BRANCH: ${{github.event.inputs.branch}}
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .confign1try0619
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  build1:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: Package Armvirt as OpenWrt
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: wget -O https://github.com/very20101/Openwrt_N1_try/releases/download/2022.09.12-1741/openwrt-armvirt-64-default-rootfs.tar.gz /home/runner/work/Openwrt_N1_try/Openwrt_N1_try/openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_VERSION_NAME: 5.15.60
        
    - name: Upload OpenWrt Firmware to Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: openwrt_armvirt_${{ env.PACKAGED_OUTPUTDATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*
        body: | 
          This is OpenWrt firmware for Armvirt 64 
          * Firmware information
          Default IP: 192.168.1.100
          Default username: root
          Default password: password
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 30
        keep_minimum_runs: 6

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
