#========================================================================================================================
# https://github.com/very20101/N1_try
# Description: Use Releases file to packaging
# Code modified from https://github.com/quanjindeng/Actions_OpenWrt-Amlogic
#========================================================================================================================

name: Pack_ARMv8_alt

on:
  repository_dispatch:
  workflow_dispatch:
  
  schedule:
    - cron: 40 18 */2 * *
env:
   
  OPENWRT_TAG: ARMv8_alt
  TZ: Asia/Shanghai 
    
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Armvirt Firmware
      id: download
      run: |
        FIRMWARE_PATH=openwrt/bin/targets/armvirt/64
        [ -d $FIRMWARE_PATH ] || mkdir -p $FIRMWARE_PATH
        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/download/OpenWrt-NewK" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
        wget -q -P $FIRMWARE_PATH https://github.com/very20101/Openwrt_N1_try/releases/download/OpenWrt-NewK/openwrt-armvirt-64-generic-rootfs.tar.gz
        echo "status=success" >> $GITHUB_OUTPUT
          
    - name: Package Armvirt as OpenWrt
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/*rootfs.tar.gz
        openwrt_board: s905d
        openwrt_kernel: 5.15.90
        gh_token: ${{ secrets.GH_TOKEN }}


    - name: Upload OpenWrt To Release
      uses: ncipollo/release-action@v1
      with:
        name: ARMv8_alt
        allowUpdates: true
        removeArtifacts: true
        tag: ${{ env.OPENWRT_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        body: |
          **This is OpenWrt Firmware for Armvirt 64**
          * 这是 ARMv8 精简版
          默认 IP：192.168.1.100 默认密码：password
          安装到 EMMC：系统 → 晶晨宝盒 → 安装 OpenWrt → 选择型号 → 安装
          升级 OpenWrt：系统 → 晶晨宝盒 → 手动上传更新 或者 在线下载更新
          当前使用版本:【编译前的最后一次➦[主源码](https://github.com/openwrt/openwrt)更新记录】
          ${{ env.VERSION_INFO }}
